
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jahnavi
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    //String driver="apache_derby_net";
    String url="jdbc:derby://localhost:1527/hotel";
    String user="root";
    String pass="root";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        tf6 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tf2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tf9 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(null);

        b5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 153, 153));
        b5.setText("UPDATE");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel4.add(b5);
        b5.setBounds(160, 270, 130, 50);

        b6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 153, 153));
        b6.setText("DELETE");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel4.add(b6);
        b6.setBounds(320, 270, 140, 50);

        b4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 153, 153));
        b4.setText("INSERT");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel4.add(b4);
        b4.setBounds(10, 270, 130, 50);

        tf6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        jPanel4.add(tf6);
        tf6.setBounds(240, 160, 170, 50);

        tf5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        jPanel4.add(tf5);
        tf5.setBounds(240, 90, 170, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Price");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(70, 170, 60, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("New Item");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(70, 100, 120, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("ADD NEW ITEM");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(90, 10, 281, 44);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\jahnavi\\Desktop\\java\\food.jpg")); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 0, 480, 380);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Item", jPanel2);

        jPanel3.setLayout(null);

        tf2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(tf2);
        tf2.setBounds(220, 130, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Waiter");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 140, 120, 29);

        b3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b3.setText("DELETE");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);
        b3.setBounds(40, 310, 150, 37);

        b2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b2.setText("UPDATE");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel3.add(b2);
        b2.setBounds(40, 250, 150, 37);

        b1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b1.setText("INSERT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel3.add(b1);
        b1.setBounds(40, 190, 150, 37);

        tf1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel3.add(tf1);
        tf1.setBounds(220, 80, 150, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Table No");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 80, 120, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("TABLE");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(160, 10, 160, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\jahnavi\\Desktop\\java\\table.jpg")); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 440, 370);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Table", jPanel1);

        jPanel6.setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);
        jButton3.setBounds(339, 320, 130, 37);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(190, 320, 131, 37);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(30, 320, 140, 37);

        tf9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tf9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf9ActionPerformed(evt);
            }
        });
        jPanel6.add(tf9);
        tf9.setBounds(310, 250, 140, 35);

        tf8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(tf8);
        tf8.setBounds(310, 190, 140, 35);

        tf7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel6.add(tf7);
        tf7.setBounds(310, 130, 140, 35);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Room Type");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(60, 180, 170, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Price");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(60, 240, 100, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Room No");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(60, 120, 150, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("ROOM");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(170, 30, 140, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\jahnavi\\Desktop\\java\\room1.jpg")); // NOI18N
        jPanel6.add(jLabel9);
        jLabel9.setBounds(0, 0, 510, 390);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Room", jPanel5);

        jButton4.setText("purchase");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("purchase", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="insert into ADD_TABLE"
                    +"(TABLE_NO,WAITERNAME)"
                    +"values(?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,tf1.getText());
            pst.setString(2,tf2.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Insert successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="update ADD_TABLE set WAITERNAME=? where TABLE_NO=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,tf2.getText());
            pst.setString(2,tf1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Updated successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="delete from ADD_TABLE where TABLE_NO=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
           
            pst.setString(1,tf1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"deleted successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        
        try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="insert into ADD_ITEM"
                    +"(ITEM,PRICE)"
                    +"values(?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,tf5.getText());
            pst.setString(2,tf6.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Insert successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        
        try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="delete from ADD_ITEM where ITEM=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
           
            pst.setString(1,tf5.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"deleted successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                  

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        
       try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="update ADD_ITEM set PRICE=? where ITEM=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,tf6.getText());
            pst.setString(2,tf5.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Updated successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                  

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="update ADD_ROOM set PRICE=? where ROOM_NO=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1,tf9.getText());
            pst.setString(2,tf7.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Updated successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
       try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="insert into ADD_ROOM"
                    +"(ROOM_NO,ROOM_TYPE,PRICE)"
                    +"values(?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,tf7.getText());
            pst.setString(2,tf8.getText());
            pst.setString(3,tf9.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Insert successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
        
    }                                        

    private void tf9ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try
        {
            //Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, pass);
            String sql="delete from ADD_ROOM where ROOM_NO=?";
            PreparedStatement pst=con.prepareStatement(sql);
            
           
            pst.setString(1,tf7.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"deleted successfully");
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Purchase a= new Purchase();
       a.setVisible(true);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration                   
}
